name: martinpulgarapp
description: Martin Pulgar Construction app for ground staff to upload photos.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.6
  get_it: ^7.2.0
  dio: ^5.3.2
  image_picker: ^1.0.4
  json_annotation:
  path_provider: ^2.0.14
  intl: ^0.17.0
  image: ^4.1.2
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  integration_test:
    sdk: flutter
  test: ^1.5.1

flutter:
  uses-material-design: true